In [4]:
import pandas as pd

In [6]:
pd.__version__

'2.2.3'

In [8]:
import numpy as np
import pandas as pd
print(np.__version__)  # Check NumPy version
print(pd.__version__)  # Check Pandas version

1.26.4
2.2.3


In [8]:
products = ['A', 'B', 'C', 'D']
products

['A', 'B', 'C', 'D']

In [10]:
type(products)

list

In [20]:
product_categories = pd.Series(products)

In [22]:
product_categories

0    A
1    B
2    C
3    D
dtype: object

In [24]:
type(product_categories)

pandas.core.series.Series

In [26]:
type(pd.Series(products))

pandas.core.series.Series

In [32]:
daily_rates_dollars = pd.Series([40, 45, 50, 67])
daily_rates_dollars

0    40
1    45
2    50
3    67
dtype: int64

In [34]:
print(daily_rates_dollars)

0    40
1    45
2    50
3    67
dtype: int64


In [38]:
import numpy as np

In [40]:
array_a = np.array([10, 20, 30, 40, 50])
array_a

array([10, 20, 30, 40, 50])

In [42]:
type(array_a)

numpy.ndarray

In [44]:
series_a = pd.Series(array_a)
series_a

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [46]:
print(series_a)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [48]:
type(series_a)

pandas.core.series.Series

In [50]:
employee_names = ['Amy White', 'Jack Stewart', 'Richard Lauderdale', 'Sara Johnson']
employee_names

['Amy White', 'Jack Stewart', 'Richard Lauderdale', 'Sara Johnson']

In [52]:
type(employee_names)

list

In [54]:
employee_names_Series = pd.Series(employee_names)
employee_names_Series

0             Amy White
1          Jack Stewart
2    Richard Lauderdale
3          Sara Johnson
dtype: object

In [56]:
import pandas as pd
import numpy as np

array_age = np.array([50, 53, 35, 43])
series_age = pd.Series(array_age)
print(type(series_age))

<class 'pandas.core.series.Series'>


In [58]:
work_experience_years = pd.Series([5, 8, 3, 10])
work_experience_years

0     5
1     8
2     3
3    10
dtype: int64

In [60]:
array_b = np.array(work_experience_years)
array_b


array([ 5,  8,  3, 10])

In [62]:
import pandas as pd

work_experience_years = pd.Series([5, 8, 3, 10])

import numpy as np
array_a = np.array(work_experience_years)

print(array_a)
print(type(array_a))


[ 5  8  3 10]
<class 'numpy.ndarray'>


In [64]:
import pandas as pd

work_experience_years = pd.Series([5,8,3,10])
work_experience_years.name = "Work Experience (Yrs.)"
print(work_experience_years)

0     5
1     8
2     3
3    10
Name: Work Experience (Yrs.), dtype: int64


In [68]:
work_experience_years.name

'Work Experience (Yrs.)'

In [70]:
work_experience_years.name = "Work Experience (Yrs.)"
print(work_experience_years)

0     5
1     8
2     3
3    10
Name: Work Experience (Yrs.), dtype: int64


In [72]:
workers_age = {'Amy White': 50, 'Jack Stewart': 53, 'Richard Lauderdale': 35, 'Sara Johnson': 43}
workers_age

{'Amy White': 50,
 'Jack Stewart': 53,
 'Richard Lauderdale': 35,
 'Sara Johnson': 43}

In [74]:
type(workers_age)

dict

In [76]:
workers_age = pd.Series(workers_age)
workers_age

Amy White             50
Jack Stewart          53
Richard Lauderdale    35
Sara Johnson          43
dtype: int64

In [78]:
type(workers_age)

pandas.core.series.Series

In [80]:
workers_age.index

Index(['Amy White', 'Jack Stewart', 'Richard Lauderdale', 'Sara Johnson'], dtype='object')

In [82]:
type(workers_age.index)

pandas.core.indexes.base.Index

In [88]:
Workers_work_experience = {'Martin': 8, 'George': 5}
Workers_work_experience

{'Martin': 8, 'George': 5}

In [92]:
employees_work_exp = pd.Series(Workers_work_experience)
employees_work_exp

Martin    8
George    5
dtype: int64

In [94]:
employees_work_exp.index

Index(['Martin', 'George'], dtype='object')

In [96]:
prices_per_category = {'Product A': 22250, 'Product B': 16600, 'Product C': 12500}
prices_per_category

{'Product A': 22250, 'Product B': 16600, 'Product C': 12500}

In [100]:
prices_per_category = pd.Series(prices_per_category)
prices_per_category

Product A    22250
Product B    16600
Product C    12500
dtype: int64

In [112]:
series_a[0]

10

In [114]:
prices_per_category['Product A']

22250

In [118]:
prices_per_category[1]

/var/folders/l8/9g_kh6ws6zx2vms45pzrl6pc0000gn/T/ipykernel_623/2333564195.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  prices_per_category[1]


16600

In [130]:
series_b = pd.Series([10, 20, 30, 40, 50], index = [1, 2, 3, 4, 5])
series_b

1    10
2    20
3    30
4    40
5    50
dtype: int64

In [136]:
series_b[0]

KeyError: 0

In [138]:
employees_work_exp

Martin    8
George    5
dtype: int64

In [142]:
employees_work_exp.index

Index(['Martin', 'George'], dtype='object')

In [148]:
employees_work_exp[1]

/var/folders/l8/9g_kh6ws6zx2vms45pzrl6pc0000gn/T/ipykernel_623/63864934.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  employees_work_exp[1]


5

In [152]:
first_index = employees_work_exp.index[0]
first_index

'Martin'

In [154]:
type(first_index)

str

In [160]:
array_age = np.array([44, 54, 65, 35])
array_age

array([44, 54, 65, 35])

In [162]:
series_age = pd.Series(array_age)
series_age

0    44
1    54
2    65
3    35
dtype: int64

In [164]:
start_date_deposits = pd.Series({
    '7/04/2014'  : 2000,
    '1/02/2015'  : 2000,
    '12/08/2012' : 1000,
    '2/20/2015' : 2000,
    '10/28/2013': 2000,
    '4/19/2015' : 2000,
    '7/04/2016'  : 2000,
    '4/24/2014' : 2000,
    '9/03/2015' : 4000,
    '7/25/2016' : 2000,
    '5/01/2014' : 2000,
    '3/29/2013' : 2000,
    '10/03/2014': 2000,
    '9/18/2015' : 2500
})

In [166]:
start_date_deposits

7/04/2014     2000
1/02/2015     2000
12/08/2012    1000
2/20/2015     2000
10/28/2013    2000
4/19/2015     2000
7/04/2016     2000
4/24/2014     2000
9/03/2015     4000
7/25/2016     2000
5/01/2014     2000
3/29/2013     2000
10/03/2014    2000
9/18/2015     2500
dtype: int64

In [170]:
start_date_deposits.sum()

29500

In [172]:
start_date_deposits.min()

1000

In [174]:
start_date_deposits.max()

4000

In [182]:
start_date_deposits.idxmax()

'9/03/2015'

In [184]:
start_date_deposits.idxmin()

'12/08/2012'

In [186]:
pd.__version__

'2.2.3'

In [188]:
data = {'ProductName': ['Product A', 'Product B', 'Product C'], 'ProductPrice':[22500, 16600, 12500]}
df = pd.DataFrame(data)
df

ProductName  ProductPrice
0   Product A         22500
1   Product B         16600
2   Product C         12500

In [190]:
data = {'ProductName': ['Product A', 'Product B', 'Product C', 'Product D'], 'ProductPrice':[22500, 16600, 12500]}
df = pd.DataFrame(data)
df

ValueError: All arrays must be of the same length

In [194]:
data = {'ProductName': ['Product A', 'Product B', 'Product C'], 'ProductPrice':[22500, 16600, 12500]}
df = pd.DataFrame(data, index = ['A', 'B', 'C'])
df

ProductName  ProductPrice
A   Product A         22500
B   Product B         16600
C   Product C         12500

In [196]:
data = {'ProductName': ['Product A', 'Product B', 'Product C'], 'ProductPrice':[22500, 16600, 12500]}
product_IDS = ['A', 'B', 'C']
df = pd.DataFrame(data, product_IDS)
df

ProductName  ProductPrice
A   Product A         22500
B   Product B         16600
C   Product C         12500

In [198]:
data = [{'ProductName': 'Product A', 'ProductPrice': 22250},
        {'ProductName': 'Product B', 'ProductPrice': 16600},
        {'ProductName': 'Product C', 'ProductPrice': [12500, 100000]}]
df = pd.DataFrame(data)
df


ProductName     ProductPrice
0   Product A            22250
1   Product B            16600
2   Product C  [12500, 100000]

In [200]:
data = [{'ProductName': 'Product A', 'ProductPrice': 22250},
        {'ProductName': 'Product B', 'ProductPrice': 16600},
        {'ProductName': 'Product C', 'ProductPrice': 12500},
        {'ProductName': 'Product D'}]
df = pd.DataFrames(data)
df
       

AttributeError: module 'pandas' has no attribute 'DataFrames'

In [202]:
datafr = {'Name':['Amy White', 'Jack Stewart', 'Richard Lauderdale', 'Sara Johnson'],
    'Age':[50, 53, 35, 43], 'Work Experinece(Yrs.)': [5, 8, 3, 10]}
df = pd.DataFrame(datafr)
df


Name  Age  Work Experinece(Yrs.)
0           Amy White   50                      5
1        Jack Stewart   53                      8
2  Richard Lauderdale   35                      3
3        Sara Johnson   43                     10

In [204]:
df

Name  Age  Work Experinece(Yrs.)
0           Amy White   50                      5
1        Jack Stewart   53                      8
2  Richard Lauderdale   35                      3
3        Sara Johnson   43                     10

In [206]:
ser_products = pd.Series(['Product A', 'Product B', 'Product C'])
ser_prices = pd.Series([22250, 16600, 12500])

In [208]:
data = {'ProductName': ser_products, 'ProductPrice': ser_prices}
df = pd.DataFrame(data)
df

ProductName  ProductPrice
0   Product A         22250
1   Product B         16600
2   Product C         12500

In [210]:
ser_products = pd.Series(['Product A', 'Product B', 'Product C'], index = ['A', 'B', 'C'])
ser_prices = pd.Series([22250, 16600, 12500], index = ['A', 'B', 'C'])
data = {'ProductName': ser_products, 'ProductPrices': ser_prices}
df = pd.DataFrame(data)
df

ProductName  ProductPrices
A   Product A          22250
B   Product B          16600
C   Product C          12500

In [212]:
ser_products = pd.Series(['Product A', 'Product B', 'Product C'], index = ['A', 'B', 'C'])
ser_prices = pd.Series([22250, 16600, 12500], index = ['C', 'B', 'A'])
data = {'ProductName': ser_products, 'ProductPrices': ser_prices}
df = pd.DataFrame(data)
df

ProductName  ProductPrices
A   Product A          12500
B   Product B          16600
C   Product C          22250

In [216]:
data = [['Product A', 22250], ['Product B',  16600], ['Prodcut C', 12500]]
df = pd.DataFrame(data)
df

0      1
0  Product A  22250
1  Product B  16600
2  Prodcut C  12500

In [218]:
df.columns = ['ProductName', 'ProductPrice']
df

ProductName  ProductPrice
0   Product A         22250
1   Product B         16600
2   Prodcut C         12500

In [220]:
df = pd.DataFrame(data = [['Product A', 22250], ['Product B',  16600], ['Prodcut C', 12500]],
                 columns = ['ProductName', 'ProductPrice'],
                 index = ['A', 'B', 'C'])
df

ProductName  ProductPrice
A   Product A         22250
B   Product B         16600
C   Prodcut C         12500

In [222]:
df.shape

(3, 2)

In [224]:
ser_names = pd.Series(['Amy White', 'Jack Stewart', 'Richard Lauderdale', 'Sara Johnson'])
ser_age = pd.Series([50, 53, 35, 43])
ser_exp = pd.Series([5, 8, 3, 10])
data = {'Name': ser_names, 'Age': ser_age, 'Working Experinece(Yrs.)': ser_exp}
df = pd.DataFrame(data)
df

Name  Age  Working Experinece(Yrs.)
0           Amy White   50                         5
1        Jack Stewart   53                         8
2  Richard Lauderdale   35                         3
3        Sara Johnson   43                        10

In [228]:
data = {'Name': ser_names, 'Age': ser_age, 'Working Experinece(Yrs.)': ser_exp}
df = pd.DataFrame(data, index = [1])
df

Name  Age  Working Experinece(Yrs.)
1  Jack Stewart   53                         8

In [236]:
data = {
    "Name":['Amy White', 'Jack Stewart', 'Richard Lauderdale', 'Sara Johnson'], 
    "Age":[50, 53, 35, 43], 
    "Working Experience (Yrs.)":[5,8,3,10]}
df = pd.DataFrame(data, index = [1, 2, 3, 4])
df

Name  Age  Working Experience (Yrs.)
1           Amy White   50                          5
2        Jack Stewart   53                          8
3  Richard Lauderdale   35                          3
4        Sara Johnson   43                         10